@if($rating == 1)
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
@elseif($rating == 2)
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
@elseif($rating == 3)
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
@elseif($rating == 4)
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
@elseif($rating == 5)
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
@endif